### ISSUE TITLE
Amazing work! 

### ISSUE THREAD

**Issue by trixpan** [michaelgibson/heka-stream-aggregator#1]
Wondering why you preferred to have an external plugin instead of pushing a PR?

**Comment by michaelgibson** [comment]
Good question!....I don't remember :)
I'll have to get back to you on that.
Glad to hear this works for you!

**Comment by michaelgibson** [comment]
At least one consideration, at this point, would be a need to refactor this to be compatible with the new Filter plugin APIs before it would be considered for merge.
https://mail.mozilla.org/pipermail/heka/2015-July/000674.html

**Comment by michaelgibson** [comment]
If you feel this should be a built in component you please open an issue with:
https://github.com/mozilla-services/heka/
